# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='terapista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.Terapista'),
            preserve_default=False,
        ),
    ]
