# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20160521_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
