# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_cita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[(b'A', b'Agendada'), (b'S', b'Asistio'), (b'N', b'No asistio'), (b'C', b'Cancelada')], default=b'A', max_length=2)),
                ('indicaciones', models.CharField(max_length=256)),
                ('bebe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.Bebe')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bebe',
            name='terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Terapia'),
        ),
    ]
