# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Bebe')),
            ],
        ),
    ]
