# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terapia__tipo_terapia',
            old_name='terapia',
            new_name='terapista',
        ),
    ]
