# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapista',
            name='fecha_nacimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
