# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_terapia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapia',
            name='bebe',
        ),
        migrations.AddField(
            model_name='bebe',
            name='terapia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.Terapia'),
            preserve_default=False,
        ),
    ]
