# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20160407_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebe',
            name='terapia',
        ),
        migrations.RemoveField(
            model_name='cit',
            name='bebe',
        ),
        migrations.DeleteModel(
            name='Bebe',
        ),
        migrations.DeleteModel(
            name='Cit',
        ),
        migrations.DeleteModel(
            name='Terapia',
        ),
    ]
