# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        ('asistencia', '0003_auto_20160401_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_cita', models.DateTimeField(auto_now=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cancelo_cita', models.BooleanField()),
                ('asistio_cita', models.CharField(max_length=1)),
                ('indicaciones', models.CharField(max_length=256)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Paciente')),
            ],
        ),
    ]
