# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_cit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cit',
            name='paciente_id',
        ),
        migrations.AddField(
            model_name='cit',
            name='bebe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.Bebe'),
        ),
    ]
