# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_auto_20160401_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cit',
            name='fecha_cita',
            field=models.DateTimeField(),
        ),
    ]
