# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_auto_20160401_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cit',
            name='asistio_cita',
        ),
        migrations.RemoveField(
            model_name='cit',
            name='cancelo_cita',
        ),
        migrations.AddField(
            model_name='cit',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Agendada'), (b'S', b'Asistio'), (b'N', b'No asistio'), (b'C', b'Cancelada')], default=b'A', max_length=2),
        ),
    ]
