# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='edad_disc_molestia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'\xc2\xbfA qu\xc3\xa9 edad notaron estas molestias?'),
        ),
        migrations.AlterField(
            model_name='historialmadre',
            name='enfermedades_antes_concepcion',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'\xc2\xbfTuvo usted alguna enfermedad grave, dolencia, accidente o infecci\xc3\xb3n, antes de concebir a \xc3\xa9ste beb\xc3\xa9?'),
        ),
    ]
