# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='edad_madre',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Edad de la madre cuando naci\xc3\xb3 el beb\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='edad_padre',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Edad del padre cuando naci\xc3\xb3 el beb\xc3\xa9'),
        ),
    ]
