# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='limitaciones_movimiento',
            field=models.IntegerField(blank=True, choices=[(1, b'SI'), (2, b'NO'), (3, b'DESCONOCE')], verbose_name=b'\xc2\xbfExiste alguna limitaci\xc3\xb3n con sus movimientos?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=4, verbose_name='grupo sanguineo'),
        ),
    ]
