# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='parentezco',
            new_name='parentesco',
        ),
        migrations.AlterField(
            model_name='alimentacioncostumbres',
            name='lugar_comida_media_manana',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'media ma\xc3\xb1ana'),
        ),
        migrations.AlterField(
            model_name='alimentacioncostumbres',
            name='lugar_comida_media_tarde',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'media tarde'),
        ),
        migrations.AlterField(
            model_name='alimentacioncostumbres',
            name='lugar_comida_otro',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'otro'),
        ),
        migrations.AlterField(
            model_name='alimentacioncostumbres',
            name='tiempo_leche_materna',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'1 - 4 Meses'), (1, b'5 - 6 Meses'), (2, b'7 - 8 Meses'), (3, b'9 - 12 Meses'), (4, b'13 - 18 Meses'), (5, b'19 - 24 Meses')]),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='alteracion_desarrollo',
            field=models.NullBooleanField(verbose_name=b'\xc2\xbfHa existido alg\xc3\xban tipo de alteraci\xc3\xb3n en su desarrollo?'),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='hermano_transtorno',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name=b'\xc2\xbfCu\xc3\xa1l de los hermanos? (Orden en que naci\xc3\xb3)'),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='numero_hermanos',
            field=models.PositiveSmallIntegerField(verbose_name=b'N\xc3\xbamero de hermanos'),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='orientacion_a_institucion',
            field=models.CharField(max_length=100, verbose_name=b'Qui\xc3\xa9n los orient\xc3\xb3 a \xc3\xa9sta instituci\xc3\xb3n?'),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='tipo_enfermedad_parientes',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'Detallar el tipo de enfermedad que se ha presentado en los parientes'),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='transtorno',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Qu\xc3\xa9 transtorno?'),
        ),
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='transtorno_hermanos',
            field=models.NullBooleanField(verbose_name=b'\xc2\xbfAlguno de los hermanos tiene alg\xc3\xban tipo de transtorno?'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='jornada',
            field=models.PositiveSmallIntegerField(choices=[(0, b''), (1, b'Tiempo completo'), (2, b'Medio tiempo'), (3, b'Por horas')], verbose_name=b'jornada de trabajo'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nivel_estudio',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Primaria'), (1, b'Secundaria'), (2, b'Universidad'), (3, b'Superior')], verbose_name=b'nivel de estudio'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name=b'Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, verbose_name='grupo sanguineo'),
        ),
        migrations.AlterField(
            model_name='primerosdias',
            name='clinica_permanencia',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'\xc2\xbfCu\xc3\xa1l fue la cl\xc3\xadnica u hospital en la que permaneci\xc3\xb3 el ni\xc3\xb1o(a)?'),
        ),
        migrations.AlterField(
            model_name='primerosdias',
            name='descripcion_bebe',
            field=models.CharField(max_length=256, verbose_name=b'Describa a su beb\xc3\xa9 los 3 primeros meses de vida'),
        ),
        migrations.AlterField(
            model_name='primerosdias',
            name='descripcion_madre',
            field=models.CharField(max_length=256, verbose_name=b'\xc2\xbfC\xc3\xb3mo se sent\xc3\xada usted esos 3 primeros meses?'),
        ),
        migrations.AlterField(
            model_name='primerosdias',
            name='icteria',
            field=models.NullBooleanField(verbose_name=b'\xc2\xbfHubo alg\xc3\xban tratamiento por icteria'),
        ),
        migrations.AlterField(
            model_name='primerosdias',
            name='lugar_dormir',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xc2\xbfD\xc3\xb3nde dorm\xc3\xada el beb\xc3\xa9?'),
        ),
        migrations.AlterField(
            model_name='primerosdias',
            name='situaciones_despues_nacimiento',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'\xc2\xbfPresent\xc3\xb3 su beb\xc3\xa9 alguna de \xc3\xa9stas situaciones despu\xc3\xa9s del nacimiento?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_score',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xc2\xbfCu\xc3\xa1l fue la puntuaci\xc3\xb3n del apgar? Si no lo sabe podr\xc3\xada ayudarnos con la historia cl\xc3\xadnica de su hijo(a)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='complicaciones_nacimiento',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'\xc2\xbfEl ni\xc3\xb1o(a) tuvo alguna de \xc3\xa9stas complicaciones al nacer?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='primera_lactancia',
            field=models.PositiveSmallIntegerField(verbose_name=b'La primera vez que el beb\xc3\xa9 tom\xc3\xb3 leche fue con'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_apego_precoz',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo dur\xc3\xb3 el apego precoz?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_internado',
            field=models.DurationField(blank=True, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo permaneci\xc3\xb3 internado(a)?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_sostener_bebe',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo pas\xc3\xb3 hasta que usted pudo sostener a su beb\xc3\xa9?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tipo_contacto',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name=b'\xc2\xbfQu\xc3\xa9 tipo de contacto tuvo con su beb\xc3\xa9 mientras estuvo internado?'),
        ),
    ]
