# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160323_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_apego_precoz',
            field=models.PositiveSmallIntegerField(blank=True, default=2, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo dur\xc3\xb3 el apego precoz?'),
        ),
    ]
