# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160411_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='edad_disc_molestia',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xc2\xbfA qu\xc3\xa9 edad notaron estas molestias?'),
        ),
        migrations.AlterField(
            model_name='descripcion',
            name='limitaciones_movimiento',
            field=models.IntegerField(choices=[(1, b'SI'), (2, b'NO'), (3, b'DESCONOCE')], verbose_name=b'\xc2\xbfExiste alguna limitaci\xc3\xb3n con sus movimientos?'),
        ),
        migrations.AlterField(
            model_name='gestacion',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'\xc2\xbfCu\xc3\xa1nta fue la carga del curso prenatal?'),
        ),
        migrations.AlterField(
            model_name='gestacion',
            name='comunicacion_bebe',
            field=models.CharField(max_length=500, verbose_name=b'\xc2\xbfC\xc3\xb3mo se comunicaba con el bebe? Marque todas las opciones que desee.'),
        ),
        migrations.AlterField(
            model_name='gestacion',
            name='lugar_curso_prenatal',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'\xc2\xbfEn qu\xc3\xa9 lugar fue el curso prenatal?'),
        ),
        migrations.AlterField(
            model_name='gestacion',
            name='momento_desc_embarazo',
            field=models.CharField(max_length=250, verbose_name=b'\xc2\xbfEn qu\xc3\xa9 momento se enter\xc3\xb3 que estaba embarazada?'),
        ),
        migrations.AlterField(
            model_name='gestacion',
            name='vacuna_tetano',
            field=models.BooleanField(verbose_name=b'\xc2\xbfSe vacun\xc3\xb3 usted contra el t\xc3\xa9tano durante el embarazo?'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='datos_familiares',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hermanos_set', to='registro.DatosFamiliaresOtros'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='registro.Descripcion'),
        ),
        migrations.AlterField(
            model_name='suplementoalimenticio',
            name='alimentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplementos', to='registro.AlimentacionCostumbres'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='descripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapias', to='registro.Descripcion'),
        ),
    ]
