# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160406_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='edad_crisis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'\xc2\xbfA qu\xc3\xa9 edad fue la primera crisis?'),
        ),
        migrations.AlterField(
            model_name='descripcion',
            name='edad_disc_molestia',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name=b'\xc2\xbfA qu\xc3\xa9 edad notaron estas molestias?'),
            preserve_default=False,
        ),
    ]
