# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160324_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nacimiento',
            name='medicamentos_parto',
        ),
    ]
