# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20160406_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='tiempo_terapia',
            field=models.CharField(max_length=50, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo lleva realizando la terapia'),
        ),
    ]
