# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20160323_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacioncostumbres',
            name='motivo_suspencion_lactancia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_apego_precoz',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo dur\xc3\xb3 el apego precoz?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_internado',
            field=models.DurationField(blank=True, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo permaneci\xc3\xb3 internado(a)?'),
        ),
    ]
