# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20160323_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_internado',
            field=models.DurationField(blank=True, null=True, verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo permaneci\xc3\xb3 internado(a)?'),
        ),
    ]
