# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20160323_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerosdias',
            name='dias_permanencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Indique los d\xc3\xadas de permanencia'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_apego_precoz',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo dur\xc3\xb3 el apego precoz?'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='tiempo_internado',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name=b'\xc2\xbfCu\xc3\xa1nto tiempo permaneci\xc3\xb3 internado(a)?'),
        ),
    ]
