# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20160323_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacioncostumbres',
            name='tiempo_leche_materna',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
