# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20160324_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfamiliaresotros',
            name='hermano_transtorno',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'\xc2\xbfCu\xc3\xa1l de los hermanos? (Orden en que naci\xc3\xb3)'),
        ),
    ]
